/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
          "on-primary-fixed": "#001b3f",
          "error": "#ffb4ab",
          "surface-container-highest": "#31353d",
          "background": "#10131b",
          "secondary-fixed-dim": "#00dddd",
          "surface-container-high": "#262a32",
          "tertiary": "#ffb693",
          "on-secondary": "#003737",
          "primary-container": "#448fff",
          "on-tertiary-container": "#4c1a00",
          "tertiary-fixed": "#ffdbcc",
          "on-background": "#e0e2ed",
          "inverse-primary": "#005cbc",
          "on-primary-container": "#002859",
          "primary": "#abc7ff",
          "secondary": "#ffffff",
          "surface": "#10131b",
          "error-container": "#93000a",
          "on-error": "#690005",
          "on-primary": "#002f66",
          "tertiary-fixed-dim": "#ffb693",
          "on-tertiary": "#561f00",
          "outline": "#8b91a0",
          "primary-fixed-dim": "#abc7ff",
          "surface-container-low": "#181c23",
          "tertiary-container": "#ed6918",
          "on-secondary-container": "#007070",
          "secondary-container": "#00fbfb",
          "on-secondary-fixed": "#002020",
          "on-surface-variant": "#c1c6d7",
          "on-tertiary-fixed-variant": "#7a2f00",
          "surface-variant": "#31353d",
          "surface-dim": "#10131b",
          "surface-container": "#1c2027",
          "surface-container-lowest": "#0b0e15",
          "on-surface": "#e0e2ed",
          "inverse-on-surface": "#2d3039",
          "secondary-fixed": "#00fbfb",
          "on-secondary-fixed-variant": "#004f4f",
          "inverse-surface": "#e0e2ed",
          "primary-fixed": "#d7e2ff",
          "surface-bright": "#363941",
          "on-tertiary-fixed": "#351000",
          "surface-tint": "#abc7ff",
          "outline-variant": "#414754",
          "on-error-container": "#ffdad6",
          "on-primary-fixed-variant": "#004590",
          "brand-black": "#050505",
          "card-bg": "rgba(18, 18, 18, 0.8)",
          "cyan-glow": "rgba(0, 255, 255, 0.4)",
          "cyan-shadow": "rgba(0, 255, 255, 0.15)"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px",
          "bento": "28px"
      },
      "spacing": {
          "grid_gap": "24px",
          "card_padding": "32px",
          "container_padding": "40px",
          "unit": "8px"
      },
      "fontFamily": {
          "body-md": ["Inter", "sans-serif"],
          "h1": ["Inter", "sans-serif"],
          "body-lg": ["Inter", "sans-serif"],
          "h2": ["Inter", "sans-serif"],
          "label-caps": ["Inter", "sans-serif"],
          "display": ["Inter", "sans-serif"]
      },
      "fontSize": {
          "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
          "h1": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600"}],
          "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
          "h2": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
          "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "600"}],
          "display": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
